spring:
  cloud:   
   gateway:
      routes:
      - id: shoppingcartaudit
        uri: lb://shoppingcartaudit
        predicates:
        - Path=/audit/**
      - id: shoppingcartorder
        uri: lb://shoppingcartorder
        predicates:
        - Path=/order/** 
      - id: shoppingcartproductinventory
        uri: lb://shoppingcartproductinventory
        predicates:
        - Path=/inventory/** 
      - id: shoppingcartuser
        uri: lb://shoppingcartuser
        predicates:
        - Path=/user/** 
      - id: shoppingonweb
        uri: lb://shoppingonweb
        predicates:
        - Path=/cart1/** 
      

