spring:
  cloud:   
   gateway:
      routes:
      - id: shoppingcartaudit
        uri: lb://shoppingcartaudit
        predicates:
        - Path=/audit/**
      - id: shoppingcartorder
        uri: lb://shoppingcartorder
        predicates:
        - Path=/order/** 
      - id: shoppingcartproductinventory
        uri: lb://shoppingcartproductinventory
        predicates:
        - Path=/inventory/** 
      - id: shoppingcartuser
        uri: lb://shoppingcartuser
        predicates:
        - Path=/user/** 
      - id: shoppingonweb
        uri: lb://shoppingonweb
        predicates:
        - Path=/cart/** 
      

okta:
  oauth2:
    issuer: https://dev-862382.okta.com/oauth2/default
    client-id: 0oa128pyrthRSSYDd4x7
    client-secret: ilY6LcsEN43IUV1bJ0ZcNWOza7HKp3XPjyF9KNi9
